FROM maven:3.9.6-eclipse-temurin-21

# ...existing code...
RUN apt-get update && apt-get install -y \
    unzip \
    wget \
    curl \
    xvfb \
    nmap \
    dsniff \
    git \
    sudo \
    libgtk-3-0 \
    libx11-xcb1 \
    libxtst6 \
    libxrender1 \
    libxi6 \
    libdbus-1-3 \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*


USER root

WORKDIR /app

COPY pom.xml .
COPY . .

RUN xvfb-run --auto-servernum --server-args="-screen 0 1024x768x16" mvn verify -DskipUnitTests=false -X