FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    isc-dhcp-server \
    iproute2 iputils-ping net-tools curl tcpdump \
    && apt-get clean

COPY dhcpd.conf /etc/dhcp/dhcpd.conf

EXPOSE 67/udp
CMD ["dhcpd", "-f", "-d"]
FROM debian:bookworm

RUN apt-get update && apt-get install -y \
    isc-dhcp-server \
    iproute2 \
    iputils-ping \
    net-tools \
    curl \
    tcpdump \
    && apt-get clean

COPY dhcpd.conf /etc/dhcp/dhcpd.conf

EXPOSE 67/udp

CMD ["dhcpd", "-f", "-d"]
