name: Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Execute Permission Script
        run: chmod +x build.sh

      - name: Build Project
        run: sh build.sh

      - name: Check for release-drafter config
        run: |
          if [ ! -f .github/release-drafter.yml ]; then
            echo "ERROR: .github/release-drafter.yml not found. Release notes will not be generated."
            exit 1
          fi

      - name: Generate Release Notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GNPT_REPO }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gnpt.zip
          body: ${{ steps.release_notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GNPT_REPO }}
